### ISSUE TITLE
请问按照你的配置了还是报错

### ISSUE THREAD

**Issue by 735450178** [Squaregentleman/mimotion#1]
请问按照你的配置了还是报错，您本人运行成功了吗，或者有哪些需要注意的请你补充说明一下

**Comment by Squaregentleman** [comment]
我刚发现报错了 得星期六才能修复

**Comment by Squaregentleman** [comment]
修复了

**Comment by 735450178** [comment]
我的还是报错了
![QQ图片20201124173846](https://user-images.githubusercontent.com/64771597/100076354-16e71f00-2e7c-11eb-99d3-3091dabf53e7.png)

![image](https://user-images.githubusercontent.com/64771597/100076578-5150bc00-2e7c-11eb-9108-3e57cf3508d1.png)

可能是我账号问题吧

**Comment by Squaregentleman** [comment]
重新fork一下试试

**Comment by 735450178** [comment]
已解决，感谢
