### ISSUE TITLE
server酱推送错误

### ISSUE THREAD

**Issue by chihwell** [Squaregentleman/mimotion#19]
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    push_wx(sckey, push)
  File "main.py", line 124, in push_wx
    推送消息到微信
NameError: name '推送消息到微信' is not defined
Error: Process completed with exit code 1.

![image](https://user-images.githubusercontent.com/72851760/108471057-d4d84880-72c5-11eb-97a7-39659e67f03c.png)

**Comment by Squaregentleman** [comment]
这行是注释啊 有没有乱改代码

**Comment by Squaregentleman** [comment]
由于超时未回复 已自动关闭issues 如还有疑问请发送新的issues
