### ISSUE TITLE
secret中STEP自定义随机范围如何设置？

### ISSUE THREAD

**Issue by DoveBoy** [Squaregentleman/mimotion#22]
@Squaregentleman 请问secret中STEP自定义随机范围如何设置？譬如设置20000-21000随机数，使用过[20000-21000]、20000-21000、[20000]-[21000]action运行日志全都是报错，无法识别，求解答
![image](https://user-images.githubusercontent.com/19201447/109153450-e333d200-77a7-11eb-8514-194e056d3c22.png)

**Comment by zhuanke8** [comment]
[18000-25000]也是错误，直接0正常运行

**Comment by DoveBoy** [comment]
@zhuanke8 按照说明文档，直接0是2w以内，我需要2w-2w1

**Comment by susll** [comment]
![image](https://user-images.githubusercontent.com/46889782/109447367-773ebb80-7a7e-11eb-8c55-80ada58a47b8.png)
@DoveBoy  就是20000-21000吧

**Comment by Squaregentleman** [comment]
自己设置一个范围 范围内随机

**Comment by Squaregentleman** [comment]
> @Squaregentleman 请问secret中STEP自定义随机范围如何设置？譬如设置20000-21000随机数，使用过[20000-21000]、20000-21000、[20000]-[21000]action运行日志全都是报错，无法识别，求解答
> ![image](https://user-images.githubusercontent.com/19201447/109153450-e333d200-77a7-11eb-8514-194e056d3c22.png)

20000-21000 正常来说不回报错 如果报错请附上报错日志 不要中括号！！！！！！！！！

**Comment by DoveBoy** [comment]
@Squaregentleman 如果设置范围是`20000-21000`，是不是STEP直接填写`20000-21000`？

**Comment by zhuanke8** [comment]
main.py直接把0-19999的范围改为你想要的，STEP填0就行了

**Comment by Squaregentleman** [comment]
> @Squaregentleman 如果设置范围是`20000-21000`，是不是STEP直接填写`20000-21000`？

对

**Comment by DoveBoy** [comment]
@Squaregentleman Done
