### ISSUE TITLE
求本地运行的方法

### ISSUE THREAD

**Issue by plumhua** [Squaregentleman/mimotion#24]

**Comment by xianghuawe** [comment]
你们github workflow 有推送步数成功到小米运动的吗  我本地运行提示推送成功  但是小米运动里没有更新

**Comment by Squaregentleman** [comment]
> 你们github workflow 有推送步数成功到小米运动的吗 我本地运行提示推送成功 但是小米运动里没有更新

小米运动不会更新 只有绑定的才会更新

**Comment by Squaregentleman** [comment]
本地运行的方法 安装 python3
pip install requests
python main.py

**Comment by xianghuawe** [comment]
> > 你们github workflow 有推送步数成功到小米运动的吗 我本地运行提示推送成功 但是小米运动里没有更新
> 
> 小米运动不会更新 只有绑定的才会更新

好的  蟹蟹
