### ISSUE TITLE
大佬，能否增加TG的推送呢

### ISSUE THREAD

**Issue by mvc3698** [Squaregentleman/mimotion#32]
由于service酱turbo收费了，4月普通版的也不能用了，所以希望大佬能支持一下TG推送，万分感恩

**Comment by Squaregentleman** [comment]
tg推送需要机器人吧 我看看

**Comment by Squaregentleman** [comment]
我没找到tg推送的机器人 如果你知道有免费的 可以发一下网址 我对接一下

**Comment by Squaregentleman** [comment]
已经添加tg推送

**Comment by Squaregentleman** [comment]
> > 我没找到tg推送的机器人 如果你知道有免费的 可以发一下网址 我对接一下
> 
> 参考一下这个，另外建议可以选择多帐号独立分开推送
> 
> ## 3. Telegram
> ## 教程：https://gitee.com/lxk0301/jd_docker/blob/master/backUp/TG_PUSH.md
> ## 需设备可连接外网，"TG_BOT_TOKEN"和"TG_USER_ID"必须同时赋值！
> ## 下方填写自己申请@Botfather的Token，如10xxx4:AAFcqxxxxgER5uw
> export TG_BOT_TOKEN=""
> 
> ## 下方填写@getuseridbot中获取到的纯数字ID
> export TG_USER_ID=""

多账号分开推送实现起来比较麻烦，暂不考虑。
