### ISSUE TITLE
大佬能否增加BARK的推送通道。

### ISSUE THREAD

**Issue by shenmirenQUQ** [Squaregentleman/mimotion#33]
server酱收费了，不能在推送看到全部内容。能否增加bark的推送通道，感谢。

https://github.com/Finb/bark-server/blob/master/docs/API_V2.md

**Comment by Squaregentleman** [comment]
需要手动搭建的目前不考虑 如果你愿意做 可以做好之后pr到主分支

**Comment by shenmirenQUQ** [comment]
> 需要手动建造的目前不考虑如果你愿意做可以做好之后pr到主分支

有大佬做出来。。不过不是我写的 我也不好意思贴出来
