### ISSUE TITLE
请问如何设置每天随机时间执行一次任务？

### ISSUE THREAD

**Issue by yeli008** [Squaregentleman/mimotion#4]
请问如何设置每天随机时间执行一次任务？

**Comment by hzys** [comment]
github自动运行貌似必须得指定时间的

**Comment by hz378904298** [comment]
怎么启动脚本

**Comment by yeli008** [comment]
> 怎么启动脚本

你是说手动启动一次吗？在ACTION里面点击具体左边的任务，然后右边有run all workflow点了就等于手动执行。
如果你是不懂怎么填写action的一些参数，作者已经写的很详细了。

**Comment by Squaregentleman** [comment]
github无法随机启动 只能指定时间
