### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by gfw404** [Squaregentleman/mimotion#43]
Process completed with exit code 1.
请问这是什么错误？

**Comment by Squaregentleman** [comment]
请附上错误报告

**Comment by gfw404** [comment]
> 请附上错误报告

1
Run pip install requests
20
Collecting requests
21
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
22
Collecting chardet<5,>=3.0.2
23
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
24
Collecting idna<3,>=2.5
25
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
26
Collecting certifi>=2017.4.17
27
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
28
Collecting urllib3<1.27,>=1.21.1
29
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
30
Installing collected packages: urllib3, idna, chardet, certifi, requests
31
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
32
Traceback (most recent call last):
33
  File "main.py", line 218, in <module>
34
    step = str(random.randint(int(setp_array[0]),int(setp_array[1])))
35
ValueError: invalid literal for int() with base 10: '[20000'
36
Error: Process completed with exit code 1.

**Comment by Squaregentleman** [comment]
步数不要出现[]
