### ISSUE TITLE
大佬，可以加一个企业微信推送吗？server酱快黄了

### ISSUE THREAD

**Issue by afghn** [Squaregentleman/mimotion#58]
大佬，可以加一个企业微信推送吗？server酱快黄了

**Comment by Squaregentleman** [comment]
有推送的案例吗 我没有企业微信

**Comment by 13574185747** [comment]
server酱出了新的企业微信的api，麻烦大佬加下

**Comment by shuai2051** [comment]
https://github.com/shuai2051/wxpush
看一下这个

**Comment by Squaregentleman** [comment]
> server酱出了新的企业微信的api，麻烦大佬加下

server酱新的api已经添加了

**Comment by Squaregentleman** [comment]
> https://github.com/shuai2051/wxpush
> 看一下这个

好的 我有时间我写一下

**Comment by tx1538** [comment]
这个确实很好，免费又干净

**Comment by Squaregentleman** [comment]
已更新企业微信推送
