### ISSUE TITLE
按照格式设置TG无法运行  换WX推送好了

### ISSUE THREAD

**Issue by immaiker911** [Squaregentleman/mimotion#59]
Run pip install requests
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
***推送参数有误！
Traceback (most recent call last):
  File "main.py", line 218, in <module>
    step = str(random.randint(int(setp_array[0]),int(setp_array[1])))
ValueError: invalid literal for int() with base 10: '[20000'
Error: Process completed with exit code 1.

**Comment by Squaregentleman** [comment]
步数请不要包含 []

**Comment by immaiker911** [comment]
好的 我试试吧 感谢大佬
