### ISSUE TITLE
今天使用显示成功但是实际已经失效了

### ISSUE THREAD

**Issue by longwangv1w2** [Squaregentleman/mimotion#6]
rt

**Comment by Squaregentleman** [comment]
确实 昨天提示成功了但是没刷成功
具体怎么回事不知道 得等多几天看看情况

**Comment by longwangv1w2** [comment]
我发现支付宝可以刷到步数，小米内部不显示步数，微信同样不行，这能是哪里出现问题了呢？

**Comment by yeli008** [comment]
之前稳定使用个把月了，今天显示微信步数刷新成功，结果到微信一看没刷成功，重新运行好几次，问题依旧。

**Comment by hzys** [comment]
难道是接口失效了？

**Comment by yeli008** [comment]
> 设置

果然可以哈哈，万能的网友分享。

**Comment by longwangv1w2** [comment]
> 已经解决，小米运动->设置->账号->注销账号->清空数据,然后重新登录,重新绑定支付宝就行了

我自己实测无效，但是发现了一个更有意思的事情，我用https://muxui.com/tool/step/的接口试了下。
我的微信能同步了，支付宝不行了......这也太扯淡了

**Comment by jw10126121** [comment]
建议添加钉钉推送

**Comment by hzys** [comment]
> 我自己实测无效，但是发现了一个更有意思的事情，我用[https://muxui.com/tool/step/的接口试了下。](https://muxui.com/tool/step/%E7%9A%84%E6%8E%A5%E5%8F%A3%E8%AF%95%E4%BA%86%E4%B8%8B%E3%80%82)
> 我的微信能同步了，支付宝不行了......这也太扯淡了

貌似现在会检测刷数据封号了

**Comment by Squaregentleman** [comment]
> 建议添加钉钉推送

可以自行添加后提交pr

**Comment by Squaregentleman** [comment]
> > 我自己实测无效，但是发现了一个更有意思的事情，我用[https://muxui.com/tool/step/的接口试了下。](https://muxui.com/tool/step/%E7%9A%84%E6%8E%A5%E5%8F%A3%E8%AF%95%E4%BA%86%E4%B8%8B%E3%80%82)
> > 我的微信能同步了，支付宝不行了......这也太扯淡了
> 
> 貌似现在会检测刷数据封号了

会封一次 之后就稳定了

**Comment by longwangv1w2** [comment]
> > > 我自己实测无效，但是发现了一个更有意思的事情，我用[https://muxui.com/tool/step/的接口试了下。](https://muxui.com/tool/step/%E7%9A%84%E6%8E%A5%E5%8F%A3%E8%AF%95%E4%BA%86%E4%B8%8B%E3%80%82)
> > > 我的微信能同步了，支付宝不行了......这也太扯淡了
> > 
> > 
> > 貌似现在会检测刷数据封号了
> 
> 会封一次 之后就稳定了

我至少封了3次了，你们现在可以用这个脚本嘛？我用了还是不行，最近都是用的其他的

**Comment by Squaregentleman** [comment]
> > > > 我自己实测无效，但是发现了一个更有意思的事情，我用[https://muxui.com/tool/step/的接口试了下。](https://muxui.com/tool/step/%E7%9A%84%E6%8E%A5%E5%8F%A3%E8%AF%95%E4%BA%86%E4%B8%8B%E3%80%82)
> > > > 我的微信能同步了，支付宝不行了......这也太扯淡了
> > > 
> > > 
> > > 貌似现在会检测刷数据封号了
> > 
> > 
> > 会封一次 之后就稳定了
> 
> 我至少封了3次了，你们现在可以用这个脚本嘛？我用了还是不行，最近都是用的其他的

我封了一次 到现在一切正常

**Comment by Squaregentleman** [comment]
目前已经稳定 未发现问题 如果还有问题 请发issues
