### ISSUE TITLE
提示账号密码数量不对

### ISSUE THREAD

**Issue by tx1538** [Squaregentleman/mimotion#76]
之前用了几天后突然不运行了，这几天也没管他  今天删除库重新fork以后 设置好 一直提示数量不对 重新设置几次还是这样
Run pip install requests
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.7.10/x64/bin/python -m pip install --upgrade pip' command.
用户名和密码数量不对

**Comment by Squaregentleman** [comment]
代码里写的是分割#
然后判断账号和密码的数量是否对的上
我也不知道你这是什么情况

**Comment by tx1538** [comment]
> 代码里写的是分割#
> 然后判断账号和密码的数量是否对的上
> 我也不知道你这是什么情况

删除参数重新设置后 刷步数可以了。但好像又提示推送失败
我设置的是企业微信推送Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.7.10/x64/bin/python -m pip install --upgrade pip' command.
企业微信推送参数有误！
1818****7772: [2021-04-27 09:52:13] 修改步数（23362）success
1538****5571: [2021-04-27 09:52:13] 修改步数（23912）success
1323****7717: [2021-04-27 09:52:13] 修改步数（21338）success
Traceback (most recent call last):
1538****8883: [2021-04-27 09:52:13] 修改步数（21203）success
  File "main.py", line 287, in <module>
    wxpush(push, sl[0], sl[1], sl[2])
  File "main.py", line 237, in wxpush
    send_message(msg, usr)
  File "main.py", line 204, in send_message
    req_urls = req_url + get_access_token(base_url, corpid, corpsecret)
  File "main.py", line 199, in get_access_token
    access_token = resp['access_token']
KeyError: 'access_token'
Error: Process completed with exit code 1.

**Comment by tx1538** [comment]
发现问题在哪了、大佬的脚本默认使用的AgentId是1000002，而我如果是用其他的应用去推送就会提示失败，而且但其中一个参数失败的时候，他也会提示账号密码数量不对。所以建议可以和其他脚本一样，能够自定义 应用ID

**Comment by Squaregentleman** [comment]
自定义 应用id 我有时间加上

**Comment by Squaregentleman** [comment]
已添加
