### ISSUE TITLE
能否支持pushplus

### ISSUE THREAD

**Issue by kyfour** [Squaregentleman/mimotion#79]
0.0自己试了改，结果发现不会改，能不能改下支持pushplus

**Comment by Squaregentleman** [comment]
有接口案例吗

**Comment by kyfour** [comment]
> 有接口案例吗


参数名称 | 是否必填 | 默认值 | 说明
-- | -- | -- | --
token | 是 | 无 | 用户令牌，可直接加到请求地址后，如：http://www.pushplus.plus/send/{token}
title | 否 | 无 | 消息标题
content | 是 | 无 | 具体消息内容，根据不同template支持不同格式
topic | 否 | 无 | 群组编码，不填仅发送给自己；channel为webhook时无效
template | 否 | html | 发送模板
channel | 否 | wechat | 发送渠道
webhook | 否 | 无 | webhook编码，仅在channel使用webhook渠道和CP渠道时需要填写

大概是这样的--因为jd_scripts和https://github.com/Today-to-Lsp/dailycheckin这个库都有pushplus的推送，所以想咨询下

**Comment by Squaregentleman** [comment]
已添加
