### ISSUE TITLE
不懂什么问题

### ISSUE THREAD

**Issue by fckcg** [Squaregentleman/mimotion#80]
Run pip install requests
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/opt/hostedtoolcache/Python/3.7.10/x64/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "main.py", line 279, in <module>
    push += main(user_list[line], passwd_list[line], step) + '\n'
  File "main.py", line 73, in main
    login_token,userid = login(user,password)
  File "main.py", line 31, in login
    location = r1.headers["Location"]
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Error: Process completed with exit code 1.

**Comment by fckcg** [comment]
账号密码在小米运动app正常登陆

**Comment by fckcg** [comment]
Run pip install requests
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Installing collected packages: urllib3, idna, chardet, certifi, requests
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m/UNKNOWN
sysconfig: /opt/hostedtoolcache/Python/3.7.10/x64/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
Successfully installed certifi-2020.12.5 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.4
Traceback (most recent call last):
  File "main.py", line 279, in <module>
    push += main(user_list[line], passwd_list[line], step) + '\n'
  File "main.py", line 73, in main
    login_token,userid = login(user,password)
  File "main.py", line 31, in login
    location = r1.headers["Location"]
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
Error: Process completed with exit code 1.

**Comment by Squaregentleman** [comment]
这个提示是账号或密码错误才会出现的
注意不是小米账号 是 小米运动账号

**Comment by fckcg** [comment]
搞定了，不是账号密码，是前面几个参数的问题 还有一个问题就是不会自动启动，我设置了cron 是18点启动 但是没自动运行

**Comment by Squaregentleman** [comment]
> 搞定了，不是账号密码，是前面几个参数的问题 还有一个问题就是不会自动启动，我设置了cron 是18点启动 但是没自动运行

这个具体不知道怎么回事 可能是github的原因

**Comment by fckcg** [comment]
好的，谢谢
