### ISSUE TITLE
微信运动可以吗？

### ISSUE THREAD

**Issue by generaljun** [Squaregentleman/mimotion#88]
在小米运动里面，绑定微信都华米科技，然后微信里面选择数据来源三华米科技，可以刷微信都步数吗？

**Comment by Squaregentleman** [comment]
小米运动绑定微信就行

**Comment by generaljun** [comment]
小米11 测试 wx不能同步。小米5X，刷的MIUI9开发版，测试可以完美修改。

**Comment by generaljun** [comment]
> 小米运动绑定微信就行

嗯嗯，微信可以修改。如果改不了，就是手机问题了。
