### ISSUE TITLE
今天跑不动了

### ISSUE THREAD

**Issue by lin365863103** [Squaregentleman/mimotion#90]
今天跑不动了

**Comment by Squaregentleman** [comment]
请附上日志

**Comment by lin365863103** [comment]
![Screenshot_20210516_201925_mark via](https://user-images.githubusercontent.com/75086375/118396861-0cb41980-b684-11eb-9018-b4e2d4bebc27.jpg)
没有日志哇，build不能点，小白不懂。

**Comment by a417707897** [comment]
我也是一样的问题。。。。

**Comment by zhuanke8** [comment]
同失败

**Comment by lin365863103** [comment]
g
